[package]
name = "monitoring_agent"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.193", features = ["derive"] }  # For serializing/deserializing.
serde_json = "1.0.108"                                  # For serializing/deserializing.
tokio-cron-scheduler = "0.9.4"                          # For schduling jobs.
tokio = { version = "1.35.1", features = ["time", "rt", "sync", "rt-multi-thread"] }

