[workspace]
resolver = "2"

members = [ 
    "monitoring-agent-daemon",
    "monitoring-agent-daemon",
    "monitoring-agent-ui"
]

[workspace.metadata.spellcheck]
config = "spellcheck.toml"


[profile.release]
lto = true